spring.application.name: weather-service
server.port: 8081
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart,health,info,beans,env
grpc:
  server:
    security:
      enabled: true
      certificateChain: classpath:server.crt
      privateKey: classpath:server.key
