spring.application.name: conditions-service
server.port: 8082
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart,health,info,beans,env
