logging.level.root: DEBUG
spring.application.name: gateway-service
server.connection-timeout: 2000
server:
  port: 8082
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gateway.p12
    key-store-password: password
    key-alias: gateway
