spring.application.name: gateway-service
server.connection-timeout: 2000
server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gateway.p12
    key-store-password: password
    key-alias: gateway
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: ap
          uri: lb://airport-service/
          predicates:
            - Path=/airport/**
          filters:
            - StripPrefix=1
        - id: wx
          uri: lb://weather-service/
          predicates:
            - Path=/weather/**
          filters:
            - StripPrefix=1
        - id: cond
          uri: lb://conditions-service/
          predicates:
            - Path=/conditions/**
          filters:
            - StripPrefix=1
