apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  selector:
    app: weather-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: gcr.io/build-better-deploy-faster/weather-service
          ports:
            - containerPort: 9090
