apiVersion: v1
kind: Service
metadata:
  name: airport-service
  labels:
    app: airport-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: airport-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airport-service
  labels:
    app: airport-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airport-service
  template:
    metadata:
      labels:
        app: airport-service
    spec:
      containers:
        - name: airport-service
          image: gcr.io/aviralmansingka-pulumi-gke/airport-service
