spring.application.name: airport-service
server.port: 8080
management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart,health,info,beans,env
