name: airport-service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"
      - run: ./airport-service/gradlew build --no-daemon
